DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `categories` (`id`, `name`, `type`, `created_at`, `updated_at`) VALUES ('1', 'Meetings', 'event', NULL, NULL),
('2', 'Rally', 'event', NULL, NULL),
('3', 'Born', 'event', NULL, NULL),
('4', 'Death', 'event', NULL, NULL),
('5', 'Engagement', 'event', NULL, NULL),
('6', 'Marriage', 'event', NULL, NULL),
('7', 'Samuhik vivah', 'event', NULL, NULL),
('8', 'Puja - Havan - Vastu', 'event', NULL, NULL),
('9', 'Bhandaro', 'event', NULL, NULL),
('10', 'Congratulations', 'event', NULL, NULL),
('11', 'Party & Celebration', 'event', NULL, NULL),
('12', 'Pustak Vitran', 'event', NULL, NULL),
('13', 'Donatation', 'event', NULL, NULL),
('14', 'Create Category', 'event', NULL, NULL),
('15', 'Personal', 'page', NULL, NULL),
('16', 'Local Business or Place', 'page', NULL, NULL),
('17', 'Brand or Product', 'page', NULL, NULL),
('18', 'Company Organization or Institution', 'page', NULL, NULL),
('19', 'Community (Events)', 'page', NULL, NULL),
('20', 'Entertainment', 'page', NULL, NULL),
('21', 'Education', 'page', NULL, NULL),
('22', 'Business & Finance', 'page', NULL, NULL),
('23', 'Stock Market', 'page', NULL, NULL),
('24', 'Technology', 'page', NULL, NULL),
('25', 'Politics', 'page', NULL, NULL),
('26', 'Sports', 'page', NULL, NULL),
('27', 'Media', 'page', NULL, NULL);
